### PR TITLE
added windows os support, speed tested under 600ms!

### PR DESCRIPTION
**Pull request by techno-express**
To address some parts of issue https://github.com/spatie/async/issues/4

This is to make an record and to match https://github.com/uppes/parallel, before an big change in terminology used.
For commits https://github.com/uppes/parallel/commits/master

### CODE REVIEW

**Comment by techno-express** [comment]
For review, not sure windows support is really desired by your users. Anyway, I have different plans for the project. just showing it's possible without much overhead, and very close to the same speed results.

**Comment by brendt** [comment]
Hey, pretty cool you got this working! Windows support is indeed not desired for this package, and I don't want to add stuff that we cannot justify maintain in the long run. Nevertheless thanks for sharing! I'll close the PR, but if someone really wants this package on Windows, they could look at this PR!

**Comment by samuelgfeller** [comment]
Oh man, I would have LOVED seeing it work on Windows.

**Comment by techno-express** [comment]
The author introduced an excellent concept, but unfortunately made it very restricted from the start, and have recently even further stop testing on Windows.

I have exported out various concepts and changes/rewrites thru different project names. 
The final one is https://github.com/symplely/spawn

**Pull request closed without merging**
