### PR TITLE
Require pcntl extension in Composer

### PR DESCRIPTION
**Pull request by m1guelpf**

### CODE REVIEW

**Comment by m1guelpf** [comment]
Looks like tests are failing for an unrelated issue.

**Comment by bomoko** [comment]
Hi there!
Quick question about this - isn't the [synchronous fallback](https://github.com/spatie/async#synchronous-fallback) supposed to obviate the need for the extension to be installed?
This fallback behaviour is quite an attractive aspect of this library (for me, at least).

**Comment by brendt** [comment]
It's indeed expected behaviour that pcntl is not required. Is there any specific reason you want this PRd in @m1guelpf ?

**Comment by m1guelpf** [comment]
@brendt Well, composer install errored in my pc when this extension was missing. Is it required by a submodule?

**Pull request closed without merging**
