### PR TITLE
Use fitting version of PHPUnit in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
https://phpunit.de/supported-versions.html

### CODE REVIEW

**Comment by szepeviktor** [comment]
@brendt Success 🍏 

Only `Spatie\Async\Tests\PoolTest::it_will_automatically_schedule_synchronous_tasks_if_pcntl_not_supported` fails.

**Comment by szepeviktor** [comment]
> Only `Spatie\Async\Tests\PoolTest::it_will_automatically_schedule_synchronous_tasks_if_pcntl_not_supported` fails.

If it requires pcntl extension to be unavailable please move it to another PHPUnit group. Then I sort it out in CI.

**Comment by szepeviktor** [comment]
@spatie-bot Please reopen.

**Comment by brendt** [comment]
I'll need to take a closer look, since actions currently are also failing on master. I'll come back to this

**Comment by szepeviktor** [comment]
@brendt How we ended up!

**Comment by brendt** [comment]
This is not really on my priority list right now, I'll make sure to do the necessary updates when we're  tagging a new major release or significant feature.

**Pull request closed without merging**
