### PR TITLE
Bugfix handling exception in synchronous process

### PR DESCRIPTION
**Pull request by vuongxuongminh**
Add an abstract method `resolveErrorOutput` to `ProcessCallbacks` trait currently only `ParallelProcess` implement it.

### CODE REVIEW

**Comment by brendt** [comment]
What's the added value of this PR?

**Comment by vuongxuongminh** [comment]
Currently only `ParallelProcess` having `resolveErrorOutput` method and it call in `ProcessCallbacks` [#L54](https://github.com/spatie/async/blob/master/src/Process/ProcessCallbacks.php#L54) but `SynchronousProcess` don't have this method and when an exception throw in synchronous task, an error unknown method `resolveErrorOutput` will be throw can not handling `catch` event of process. The added value is add a `resolveErrorOutput` to `SynchronousProcess` to fix issue above.

**Comment by brendt** [comment]
Right, got it! Can you fix the StyleCI errors still?

**Comment by vuongxuongminh** [comment]
Yes, i did it. Sorry for losing your time.

**Comment by EspadaV8** [comment]
Is there anything needed to get this merged? We've noticed this issue too and have a work around, but it would be nice if there was a bugfix released :)

**Comment by brendt** [comment]
I lost track of this one because of some personal stuff going on. I'll tag it right away

**Comment by EspadaV8** [comment]
No worries. Thanks for that 😄

**Comment by brendt** [comment]
Here we go! https://github.com/spatie/async/releases/tag/1.0.4

It might take a minute or 2 before packagist knows of the latest release.

**Pull request merged**
